### ISSUE TITLE
Where to start if LED won't work

### ISSUE THREAD

**Issue by YujiTFD** [lubeda/EsphoMaTrix#10]
Hi.
Sorry for garbled issue, accidentally hit Enter while typing.

Don't hesitate to tell me if I'm asking something wrong, but I'm not sure where to start debugging.
I use 30-pin WROOM 32 for this project, want to build an informer from a 8x32 LED panel, I'm using standart GPIO16(D2) for data and VIN/GDN for LED power.
ESP32 was tested with WLED project so I know it works fine, power supply is USB charger 5V/3A.
For testing purposes I removed icons from ESPHome code and changed font file with bitmap Cozette (https://github.com/slavfox/Cozette, font size 13px), everything else left untouched.

On your video switching power makes matrix display "01.01", but my stays unlit blank, what could I miss?

Again, feel free to move issue if I'm not supposed to ask such things here.

Thank you advance.

**Comment by jd1** [comment]
Try to start without this component and configure only light with 'platform: neopixelbus'. If this also doesn't work, check your wiring.

**Comment by YujiTFD** [comment]
Yes, I got it working with monobit after which bitmap cozette worked too, not sure what was causing problem. Still, cozette 13px looks trancated from the top, like this (I sent on screen "123", don't mind reflection). Is it something amendable?
![IMG_1534](https://user-images.githubusercontent.com/19327740/167931084-45311cf3-b55a-41e9-bcb3-3f839ea860b3.jpg)

**Comment by lubeda** [comment]
You can scale the font with the size parameter in the [font definition](https://esphome.io/components/display/index.html?highlight=size#fonts). But the font is not readable when scaled to fit!
