### ISSUE TITLE
Display problem since update

### ISSUE THREAD

**Issue by bobdivx** [lubeda/EsphoMaTrix#100]
Hello, a few months ago I installed your project on my esp 8266, today I only have two lines left to display.
My code worked perfectly, today impossible to update.

`  
substitutions:
  devicename: esphomatrix
  mypin: GPIO16
  board: mhetesp32minikit

external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EsphoMaTrix

esphome:
  name: $devicename
  on_boot:
    priority: -100
    then: 
      - ehmtx.text.color:
          id: rgb8x32
          red: !lambda return 200;
          blue: !lambda return 170;
      - ehmtx.today.color:
          id: rgb8x32
          red: !lambda return 10;
          green: !lambda return 250;
      - ehmtx.clock.color:
          id: rgb8x32
          red: !lambda return 50;
          green: !lambda return 150;
          blue: !lambda return 230;
      - ehmtx.weekday.color:
          id: rgb8x32
          red: !lambda return 250;
          green: !lambda return 50;
          blue: !lambda return 30;

esp32:
  board: $board
  

binary_sensor:
  - platform: status
    name: "$devicename Status"

font:
  - file: fonts/monobit.ttf
    id: ehmtx_font
    size: 16
    glyphs:  |
      !?"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@<>/
logger:

# Enable Home Assistant API
api:
  services:
    - service: alarm
      variables:
        icon_name: string
        text: string
      then:
        lambda: |-
          id(rgb8x32)->add_screen(icon_name, text, 7, true);
          id(rgb8x32)->force_screen(icon_name);
    - service: screen
      variables:
        icon_name: string
        text: string
      then:
        lambda: |-
          id(rgb8x32)->add_screen(icon_name, text, 1, false);
    - service: brightness
      variables:
        brightness: int
      then:
        lambda: |-
          id(rgb8x32)->set_brightness(brightness);
    - service: status
      then:
        lambda: |-
          id(rgb8x32)->get_status();
    - service: del_screen
      variables:
        icon_name: string
      then:
        lambda: |-
          id(rgb8x32)->del_screen(icon_name);
    - service: indicator_on
      variables:
        r: int
        g: int
        b: int
      then:
        lambda: |-
          id(rgb8x32)->set_indicator_color(r,g,b);
          id(rgb8x32)->set_indicator_on();
    - service: text_color
      variables:
        r: int
        g: int
        b: int
      then:
        lambda: |-
          id(rgb8x32)->set_text_color(r,g,b);
    - service: alarm_color
      variables:
        r: int
        g: int
        b: int
      then:
        lambda: |-
          id(rgb8x32)->set_alarm_color(r,g,b);
    - service: indicator_off
      then:
        lambda: |-
          id(rgb8x32)->set_indicator_off();
ota:
  password: "62e44adc9d58376602c14d454bd5660e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: "InM2TlqVfJe4"

light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    variant: WS2812
    pin: $mypin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    name: "$devicename Light"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      lambda: |-
         id(ehmtx_display)->set_enabled(false);
    on_turn_off:
       lambda: |-
         id(ehmtx_display)->set_enabled(true);
number:
  - platform: template
    name: "LED brightness"
    min_value: 40
    max_value: 150
    step: 1
    lambda: |-
      return id(rgb8x32)->get_brightness();
    set_action:
      lambda: |-
        id(rgb8x32)->set_brightness(x);
        
time:
  - platform: homeassistant
    id: ehmtx_time

display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (y % 2 == 0) {
        return x + ( y * 32);
      }
      else
      {
      return (31 - x) + ( y * 32);
      }
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();
ehmtx:
  ehmtxselect: esphomatrix
  id: rgb8x32
  show_clock: 4
  show_screen: 6
  display8x32: ehmtx_display
  time: ehmtx_time
  duration: 5
  font_id: ehmtx_font
  on_next_screen:
    lambda: |-
        ESP_LOGD("Trigger","Notification");
  icons: 
    - url: https://developer.lametric.com/content/apps/icon_thumbs/41503
      id: boot

select:
   - platform: ehmtx
     id: esphomatrix
     name: "esphomatrix"`

LOGS:
`    INFO Reading configuration /config/esphome/esphomatrix.yaml... 
    WARNING 
      WARNING If you are upgrading EsphoMaTrix from a version before 2023.4.0,
    WARNING you should read the section https://github.com/lubeda/EsphoMaTrix/#how-to-update for tipps.
    WARNING 
    INFO Detected timezone 'Europe/Paris'
    Failed config

    ehmtx: [source /config/esphome/esphomatrix.yaml:180]
  
    'time_component' is a required option for [ehmtx].
  
    [ehmtxselect] is an invalid option for [ehmtx]. Please check the indentation.
    ehmtxselect: esphomatrix
    id: rgb8x32
  
    [show_clock] is an invalid option for [ehmtx]. Did you mean [show_dow], [show_seconds], [on_next_clock]?
    show_clock: 4
  
    [show_screen] is an invalid option for [ehmtx]. Did you mean [show_seconds], [on_next_screen], [show_date]?
    show_screen: 6
  
    [display8x32] is an invalid option for [ehmtx]. Please check the indentation.
    display8x32: ehmtx_display
  
    [time] is an invalid option for [ehmtx]. Did you mean [hold_time]?
    time: ehmtx_time
  
    [duration] is an invalid option for [ehmtx]. Please check the indentation.
    duration: 5
    font_id: ehmtx_font
    on_next_screen: 
      lambda: ESP_LOGD("Trigger","Notification");
    icons: 
      - url: https://developer.lametric.com/content/apps/icon_thumbs/41503
        id: boot
      - url: https://developer.lametric.com/content/apps/icon_thumbs/7112
        id: temp_home
      
        [duration] is an invalid option for [1]. Did you mean [frame_duration]?
        duration: 250
      - url: https://developer.lametric.com/content/apps/icon_thumbs/4788
      id: alert
      duration: 250
    
     select.ehmtx: [source /config/esphome/esphomatrix.yaml:262]
  
       Platform not found: 'select.ehmtx'.
      platform: ehmtx
     id: esphomatrix
      name: esphomatrix
      required key not provided
`

**Comment by lubeda** [comment]
Did you read  https://github.com/lubeda/EsphoMaTrix/#how-to-update ?

**Comment by bobdivx** [comment]
yes I saw that, but I confess that I am a little lost, attached my file to modify but I think I missed something
[matrix.txt](https://github.com/lubeda/EsphoMaTrix/files/11301769/matrix.txt)

**Comment by lubeda** [comment]
[bobdivx.txt](https://github.com/lubeda/EsphoMaTrix/files/11301783/bobdivx.txt)

**Comment by bobdivx** [comment]
thank you very much for your time, when I want to compile I have this error


`/config/esphome/esphomatrix.yaml: In lambda function:
/config/esphome/esphomatrix.yaml:60:51: error: no matching function for call to 'esphome::EHMTX::add_screen(std::__cxx11::string&, std::__cxx11::string&, int, bool)'
           id(rgb8x32)->add_screen(icon_name, text, 7, true);
                                                   ^
In file included from src/esphome.h:21,
                 from src/main.cpp:3:
src/esphome/components/ehmtx/EHMTX.h:95:10: note: candidate: 'void esphome::EHMTX::add_screen(std::__cxx11::string, std::__cxx11::string, int, int, bool)'
     void add_screen(std::string icon, std::string text, int duration, int showt_time, bool alarm);
          ^~~~~~~~~~
src/esphome/components/ehmtx/EHMTX.h:95:10: note:   candidate expects 5 arguments, 4 provided
/config/esphome/esphomatrix.yaml: In lambda function:
/config/esphome/esphomatrix.yaml:68:52: error: no matching function for call to 'esphome::EHMTX::add_screen(std::__cxx11::string&, std::__cxx11::string&, int, bool)'
           id(rgb8x32)->add_screen(icon_name, text, 1, false);
                                                    ^
In file included from src/esphome.h:21,
                 from src/main.cpp:3:
src/esphome/components/ehmtx/EHMTX.h:95:10: note: candidate: 'void esphome::EHMTX::add_screen(std::__cxx11::string, std::__cxx11::string, int, int, bool)'
     void add_screen(std::string icon, std::string text, int duration, int showt_time, bool alarm);
          ^~~~~~~~~~
src/esphome/components/ehmtx/EHMTX.h:95:10: note:   candidate expects 5 arguments, 4 provided
/config/esphome/esphomatrix.yaml: In lambda function:
/config/esphome/esphomatrix.yaml:92:16: error: 'class esphome::EHMTX' has no member named 'set_indicator_color'; did you mean 'indicator_color'?
           id(rgb8x32)->set_indicator_color(r,g,b);
                ^~~~~~~~~~~~~~~~~~~
                indicator_color
/config/esphome/esphomatrix.yaml:93:33: error: no matching function for call to 'esphome::EHMTX::set_indicator_on()'
           id(rgb8x32)->set_indicator_on();
                                 ^
In file included from src/esphome.h:21,
                 from src/main.cpp:3:
src/esphome/components/ehmtx/EHMTX.h:106:10: note: candidate: 'void esphome::EHMTX::set_indicator_on(int, int, int)'
     void set_indicator_on(int r, int g, int b);
          ^~~~~~~~~~~~~~~~
src/esphome/components/ehmtx/EHMTX.h:106:10: note:   candidate expects 3 arguments, 0 provided
/config/esphome/esphomatrix.yaml: In lambda function:
/config/esphome/esphomatrix.yaml:117:27: error: 'icon_name' was not declared in this scope
             id(rgb8x32)->add_screen(icon_name,text,7,30,true);
                           ^~~~~~~~~
/config/esphome/esphomatrix.yaml:117:37: error: 'text' was not declared in this scope
             id(rgb8x32)->add_screen(icon_name,text,7,30,true);
                                     ^~~~
/config/esphome/esphomatrix.yaml:117:37: note: suggested alternative: 'atexit'
             id(rgb8x32)->add_screen(icon_name,text,7,30,true);
                                     ^~~~
                                     atexit
Compiling /data/esphomatrix/.pioenvs/esphomatrix/lib64d/WiFi/WiFiUdp.cpp.o
Compiling /data/esphomatrix/.pioenvs/esphomatrix/lib915/ESPmDNS/ESPmDNS.cpp.o
Compiling /data/esphomatrix/.pioenvs/esphomatrix/libbc6/Update/HttpsOTAUpdate.cpp.o
Compiling /data/esphomatrix/.pioenvs/esphomatrix/libbc6/Update/Updater.cpp.o
*** [/data/esphomatrix/.pioenvs/esphomatrix/src/main.cpp.o] Error 1
========================= [FAILED] Took 12.73 seconds =========================`

**Comment by bobdivx** [comment]
I have modified the lines as in your cedpanat documentation, I only have one error left:
esphome: $devicename


[esphomatrix.yaml.txt](https://github.com/lubeda/EsphoMaTrix/files/11302072/esphomatrix.yaml.txt)
