### ISSUE TITLE
Allow Flipping the Display 180 degrees

### ISSUE THREAD

**Issue by carlos-sarmiento** [lubeda/EsphoMaTrix#105]
I have a Ulanzi TC001 which I would like to install upside down. I was looking through the documentation and couldn't see a mechanism to flip/rotate the screen by 180 degrees. 

Is this possible?

**Comment by lubeda** [comment]
Of course, but not with my component.

See the [wiki](https://github.com/lubeda/EspHoMaTriXv2/wiki/Ulanzi-TC001-turn-display-upside-down) of the newer version of my tool, which also works for the older version you are using!
