### ISSUE TITLE
Screen with Color

### ISSUE THREAD

**Issue by michisbarq** [lubeda/EsphoMaTrix#121]
Hi,
I add a Screen in HA and I want this Screen in a specific Text Color.

Actual I call to Services. Add_Screen and Text_Color.

That doesn't work very fine. Sometimes it work, sometimes not!

Is it possible to Add_Screen with a specific COLOR in RGB?

**Comment by lubeda** [comment]
Hi, take a look at https://github.com/lubeda/EspHoMaTriXv2 in the 2023.9.1 branch. This is the evolution of your version, so you can expect more functionality but also the need of changing your service calls. e.g.

here you can set the color per icon: 
icon_screen => {"icon_name", "text", "lifetime", "screen_time", "default_font", "r", "g", "b"}

**Comment by michisbarq** [comment]
Thank U. I try it with my new Ulanzi Clock.
