### ISSUE TITLE
FEATURE REQUEST: Enable Separate Control of Clock, Dates and Others Display

### ISSUE THREAD

**Issue by kelvincabaldo07** [lubeda/EsphoMaTrix#17]
Is it possible to have a separate control of how long the clock, date and other details will be displayed. i am trying to figure out a way to display the date a little bit longer as i think it is displaying just about a second or even less and i cant figure out for the life of me. haha. i may just be missing some documentation but i would appreciate it if you can point me to it. thanks!

**Comment by lubeda** [comment]
each screen (also time/date) is displayed for `show_screen` seconds. In the time/date screen the clock is displayed for `show_clock` seconds. So the default time for the date is 7-5=2 seconds. You can increase `show_screen` oder decrease `show_clock`
