### ISSUE TITLE
del_screen change icon to the first icon

### ISSUE THREAD

**Issue by SgtFirepasi** [lubeda/EsphoMaTrix#26]
hello,

when I push the del_screen service from homeassistant to the display, it only change the icon to the first icon in my list and i have to send it again with this icon to really delete the screen.

**Comment by lubeda** [comment]
Yes, there is something wrong with del_screen, i've to check.

**Comment by lubeda** [comment]
Found the error, the fix will come soon

**Comment by SgtFirepasi** [comment]
Yes, with this branch it works.
Thanks for the fast support. :-)
