### ISSUE TITLE
gif inanimate

### ISSUE THREAD

**Issue by bobdivx** [lubeda/EsphoMaTrix#35]
hello my matrix is ​​perfectly functional, however the gifs are fixed, it does not move.  THANKS

**Comment by jrspowers** [comment]
hello you have to get the icons from lametric's website a lot of icons & you can also make them yourself and put them in this way it works perfectly!

```yaml
- url: https://developer.lametric.com/content/apps/icon_thumbs/37472
id: waschmaschine
```

**Comment by lubeda** [comment]
There are so many icons on the web, if the source ist correct they will work with esphomematrix.
