### ISSUE TITLE
Ulanzi support…Yay!

### ISSUE THREAD

**Issue by aptonline** [lubeda/EsphoMaTrix#37]
Great to see you have added Ulanzi support to EspHoMaTrix, I’ll look forward to flashing and giving it a go.

I see you have referenced the use of the pinouts from my [PixelIt Ulanzi repository](https://github.com/aptonline/PixelIt_Ulanzi)  in the code (which is great) and also included me in a ‘Thanks’ in the README, it’s appreciated. Could I ask however that you add @wsbtak to the thanks for all their hard work (and head scratching) to get Pixelit working on the Ulanzi? If it wasn’t for them we wouldn’t be where we are today 😀.

Thanks again and keep up the good work.

**Comment by lubeda** [comment]
Sure, I added wsbtak to the thanks section
