### ISSUE TITLE
Gifs are static

### ISSUE THREAD

**Issue by dundiffrunt** [lubeda/EsphoMaTrix#40]
Hi,

since the removal of the awtrixid feature I've changed the icons to url mode. Sadly the GIF icons don't move at all and are static.
What do I have to do to get moving icons?

Cheers
Marco

**Comment by dundiffrunt** [comment]
here's an example:

    - url: https://developer.lametric.com/content/apps/icon_thumbs/5582_icon_thumb.gif
      id: ella

**Comment by dundiffrunt** [comment]
I see what I did wrong. I'll try again with the correct URL fortmat.

**Comment by lubeda** [comment]
I see, the automagic scaling of  gif-icons isn't working all the time. But tat is port of the librarys that come from esphome and beyond my scope.
So i made a note in the README.md
