### ISSUE TITLE
add sensors from HA in loop as time

### ISSUE THREAD

**Issue by maverik80** [lubeda/EsphoMaTrix#5]
hello I congratulate you for a great job, I added this sensor:
--------------------------------------------------------
sensor:
  - platform: homeassistant
    id: istantaneo_w
    entity_id: sensor.energia_assorbita
    internal: true`
----------------------------------------------------------

but I can't put it in loop at the date and time, could you tell me how to insert it? bearing in mind that I am using the sample code

thank you very much if anyone replies

**Comment by lubeda** [comment]
The easiest way is to do it from homeassistant by an automation like this: [documentation](https://github.com/lubeda/EsphoMaTrix#use-in-automations-from-homeassistant)

`
alias: send states to ehmtx
description: ''
trigger:
  - platform: state
    entity_id: sensor.energia_assorbita                # your entity
    id: power                                                        # your icon defined on your ehmtx-device
condition: []
action:
  - service: esphome.ehmtx8266_screen            # must correspond to your device name
    data:
      icon_name: 'power'                                      # again your icon
      text: >-
        {{trigger.to_state.state}}{{trigger.to_state.attributes.unit_of_measurement}}


`
