### ISSUE TITLE
Question: How to better include turn off animation/light effect

### ISSUE THREAD

**Issue by pplucky** [lubeda/EsphoMaTrix#56]
In my awtrix matrix, there is a turn off animation whenever the display is turned off, which I think it is nice.

I built an [Addressable Lambda Effect](https://esphome.io/components/light/index.html#addressable-lambda-effect) in esphome to mimic the same animation on my Ulanzi EsphoMaTrix, assigned it to the light component and it works fine if I trigger the effect manually.

Probably there are simpler ways to achieve this, but here it is for reference, if anyone wants to use it also:
```
addressable_lambda:
  name: "ZZZ"
  update_interval: 100ms
  lambda: |-
    static int x = 0;
    if (initial_run) {
      x = 1;
      it.all() = Color(0,0,0);
    }
    // it.range() seems to include initial LED # but excludes last LED #
    switch (x) {
      case 1:
        // Line 8 - right to left (from 224)
        it.range(231, 236) = Color(255,255,255);
        x += 1;
        break;
      case 2:
        // Line 7 - left to right (from 192)
        it.range(210, 215) = Color(255,255,255);
        // Line 8 - right to left (from 224)
        it.range(231, 236) = Color(0,0,0);
        it[233] = Color(255,255,255);
        x += 1;
        break;
      case 3:
        // Line 6 - right to left (from 160)
        it.range(172, 177) = Color(255,255,255);
        // Line 7 - left to right (from 192)
        it.range(210, 215) = Color(0,0,0);
        it[211] = Color(255,255,255);
        // Line 8 - right to left (from 224)
        it[233] = Color(0,0,0);
        it[237] = Color(255,255,255);
        x += 1;
        break;
      case 4:
        // Line 5 - left to right (from 128)
        it.range(141, 146) = Color(255,255,255);
        // Line 6 - right to left (from 160)
        it.range(172, 177) = Color(0,0,0);
        it[174] = Color(255,255,255);
        // Line 7 - left to right (from 192)
        it[211] = Color(0,0,0);
        it[208] = Color(255,255,255);
        // Line 8 - right to left (from 224)
        it[237] = Color(0,0,0);
        it[240] = Color(255,255,255);
        x += 1;
        break;
      case 5:
        // Line 4 - right to left (from 96)
        it.range(111, 116) = Color(255,255,255);
        // Line 5 - left to right (from 128)
        it.range(141, 146) = Color(0,0,0);
        it[144] = Color(255,255,255);
        // Line 6 - right to left (from 160)
        it[174] = Color(0,0,0);
        it[176] = Color(255,255,255);
        // Line 7 - left to right (from 192)
        it[208] = Color(0,0,0);
        it[206] = Color(255,255,255);
        // Line 8 - right to left (from 224)
        it[240] = Color(0,0,0);
        it[242] = Color(255,255,255);
        x += 1;
        break;
      case 6:
        // Line 3 - left to right (from 64)
        it.range(75, 80) = Color(255,255,255);
        // Line 4 - right to left (from 96)
        it.range(111, 116) = Color(0,0,0);
        it[112] = Color(255,255,255);
        // Line 5 - left to right (from 128)
        it[144] = Color(0,0,0);
        it[142] = Color(255,255,255);
        // Line 6 - right to left (from 160)
        it[176] = Color(0,0,0);
        it[178] = Color(255,255,255);
        // Line 7 - left to right (from 192)
        it[206] = Color(0,0,0);
        it[204] = Color(255,255,255);
        // Line 8 - right to left (from 224)
        it[242] = Color(0,0,0);
        it[244] = Color(255,255,255);
        x += 1;
        break;
      case 7:
        // Line 2 - right to left (from 32)
        it.range(49, 54) = Color(255,255,255);
        // Line 3 - left to right (from 64)
        it.range(75, 80) = Color(0,0,0);
        it[78] = Color(255,255,255);        
        // Line 4 - right to left (from 96)
        it[112] = Color(0,0,0);
        it[114] = Color(255,255,255);
        // Line 5 - left to right (from 128)
        it[142] = Color(0,0,0);
        it[140] = Color(255,255,255);
        // Line 6 - right to left (from 160)
        it[178] = Color(0,0,0);
        it[180] = Color(255,255,255);
        // Line 7 - left to right (from 192)
        it[204] = Color(0,0,0);
        it[202] = Color(255,255,255);
        // Line 8 - right to left (from 224)
        it[244] = Color(0,0,0);
        it.range(241, 246) = Color(255,255,255);
        x += 1;
        break;
      case 8:
        // Line 1 - left to right (from 0)
        it.range(8, 13) = Color(255,255,255);
        // Line 2 - right to left (from 32)
        it.range(49, 54) = Color(0,0,0);
        it[51] = Color(255,255,255);
        // Line 3 - left to right (from 64)
        it[78] = Color(0,0,0);
        it[75] = Color(255,255,255);
        // Line 4 - right to left (from 96)
        it[114] = Color(0,0,0);
        it[117] = Color(255,255,255);
        // Line 5 - left to right (from 128)
        it[140] = Color(0,0,0);
        it[137] = Color(255,255,255);
        // Line 6 - right to left (from 160)
        it[180] = Color(0,0,0);
        it[183] = Color(255,255,255);
        // Line 7 - left to right (from 192)
        it[202] = Color(0,0,0);
        it.range(200, 206) = Color(255,255,255);
        // Line 8 - right to left (from 224)
        it.range(241, 246) = Color(0,0,0);
        x += 1;
        break;
      case 9:
        // Line 1 - left to right (from 0)
        it.range(8, 13) = Color(0,0,0);
        it[13] = Color(255,255,255);
        // Line 6 - right to left (from 160)
        it[183] = Color(0,0,0);
        it.range(178, 183) = Color(255,255,255);
        // Line 7 - left to right (from 192)
        it.range(200, 206) = Color(0,0,0);
        x += 1;
        break;
      case 10:
        // Line 5 - left to right (from 128)
        it[137] = Color(0,0,0);
        it.range(138, 143) = Color(255,255,255);
        // Line 6 - right to left (from 160)
        it.range(178, 183) = Color(0,0,0);
        x += 1;
        break;
      case 11:
        // Line 4 - right to left (from 96)
        it[117] = Color(0,0,0);
        it.range(112, 117) = Color(255,255,255);
        // Line 5 - left to right (from 128)
        it.range(138, 143) = Color(0,0,0);
        x += 1;
        break;
      case 12:
        // Line 3 - left to right (from 64)
        it[75] = Color(0,0,0);
        it.range(76, 81) = Color(255,255,255);
        // Line 4 - right to left (from 96)
        it.range(112, 117) = Color(0,0,0);
        x += 1;
        break;
      case 13:
        // Line 2 - right to left (from 32)
        it[51] = Color(0,0,0);
        it.range(46, 51) = Color(255,255,255);
        // Line 3 - left to right (from 64)
        it.range(76, 81) = Color(0,0,0);
        x += 1;
        break;
      case 14:
        // Line 1 - left to right (from 0)
        it[13] = Color(0,0,0);
        it.range(14, 19) = Color(255,255,255);
        // Line 2 - right to left (from 32)
        it.range(46, 51) = Color(0,0,0);
        x += 1;
        break;
      case 15:
        it.all() = Color(0,0,0);
        break;
    }
```

If I turn on the light with the effect, it switches from the clock to the animation. 
The "problem" is that to stop the animation, I either need: 
- to apply an effect 'None' (which actually turns on all the LEDs in the matrix, same as turning light on without any effect) or;
- directly turn off the light (which actually ["reactivates the clock"](https://github.com/lubeda/EsphoMaTrix/tree/main#use-the-light-component) - which makes sense but not when turning off the display).

So my question here is: how would you guys better include this to behave as a turn off animation? Going from clock or whatever is on the display to the animation and then display off.

Thanks for any suggestions.

**Comment by lubeda** [comment]
After a bit of thinking....

Perhaps it is best to not use an effect, instead add your code to the display lambda. But this is called every 16ms, so you have to slow down your code and disable my tick() and my draw() functions.

Even better support for 8x32 gifs.....

**Comment by pplucky** [comment]
> i think the idea with 8x32 animations would be possible with out changing the whole code.
> like 8x8 icons with scrolling text and 8x32 animations without text
> i will take a closer look.

I didn’t want to suggest that, considering the amount of priceless work you have already put into this component (thanks again for that), but that would be a perfect addition which I think a lot will appreciate.

**Comment by lubeda** [comment]
i added support for 8x32 images and animations. Their display works the same as for 8x8 icons but for 8x32 images no text will be displayed.
breaking: you have to scale all icons your self, i removed the automatic scaling

**Comment by pplucky** [comment]
> i added support for 8x32 images and animations (in the 8x32 branch). Their display works the same as for 8x8 icons but for 8x32 images no text will be displayed.

Quick test seems to work, need more time into it.

> breaking: you have to scale all icons your self, i removed the automatic scaling

Noticed the error while compiling before installing to esphome, I just wonder if it would be possible to show the whole list of non 8x8 or 8x32 images, instead of the first found from the list, to make it easier to fix without going one by one.

**Comment by lubeda** [comment]
check the recent push to 8x32. icons with wrong size are skipped with warning!

**Comment by pplucky** [comment]
For me, it is rather cumbersome to NOT to be able to specify how many times a screen is to be shown, even more with animations...

I know you have mentioned it [here](https://github.com/lubeda/EsphoMaTrix/issues/46#issuecomment-1458663539), but  I would still see it as useful, specially with animations.

To be able to achieve an animation to be shown only once (at shutdown, as per my initial question), I'd need to make sure I would delete the screen before the animation would start a second time...

**Comment by lubeda** [comment]
I understand the requirement and see the possible uses, but it is not necessary for my purposes. An implementation would require a redesign of the inner processes. 
If someone has an implementation, I am happy about every pull request.

That's why this topic is tagged with "help wanted"

**Comment by ofirsnb** [comment]
> Quick test seems to work, need more time into it.

@pplucky 
Can you share a 8x32 animation gif for testing please?

**Comment by pplucky** [comment]
> @pplucky Can you share a 8x32 animation gif for testing please?

Sure, here is the 8x32 GIF I generated for the above effect:
![ZZZ](https://user-images.githubusercontent.com/16407309/224850723-634c9b2d-55d9-44f2-9f93-765c0485b090.gif)

**Comment by lubeda** [comment]
starting with 2023.4.0 there is a parameter show_time for each screen, you can set a longer displaytime per screen.
Please read the "how to update" section in the new README.md before trying!

If you included your sample gif under the id `sleeping` you can display it for e.g. 60 seconds with this call:

```
service: esphome.ulanzi_add_screen
data:
  icon_name: sleeping
  text: ehmtx
  screen_time: 60
```

With the possibility to disable the clock you can show this animation all day long.
