### ISSUE TITLE
Add add_screen and force_screen to README?

### ISSUE THREAD

**Issue by pplucky** [lubeda/EsphoMaTrix#64]
Not sure if I should add default provided services `add_screen` (which can be used for regular screens or alarms and specify duration) and `force_screen` to [README](https://github.com/lubeda/EsphoMaTrix/blob/main/README.md), in the [services part](https://github.com/lubeda/EsphoMaTrix#services), also included in #63?

What do you think @lubeda?

**Comment by lubeda** [comment]
Hi, i'm happy if you could add these commands to the docu. The default service are the standard possibilities of [EsphoMaTrix](https://github.com/lubeda/EsphoMaTrix). So i think its the right way to define them als default. 

Thanx for your help!
