### ISSUE TITLE
2023.03.05 & brightness

### ISSUE THREAD

**Issue by jjvelar** [lubeda/EsphoMaTrix#65]
Hi,
After updating to 2023.03.05, brightness service and this code to show and adjust brightness are no longer working: no matter what interger value you user with "brightness" service, or how much you move the brightness slider, return brightness value is always 0.
But real brightness is not 0 as figures and icons are visible in the screen.
Please advise.

`number:
  - platform: template
    name: "$devicename Brightness"
    id: brightness_value
    min_value: 0
    max_value: 255
    step: 1
    lambda: |-
      return id(rgb8x32)->get_brightness();
    set_action:
      lambda: |-
        id(rgb8x32)->set_brightness(x);`

**Comment by lubeda** [comment]
There was an error in my code. Its fixed in the 8x32 branch, wich will be released soon.
