### ISSUE TITLE
Gauge scaling seems wrong

### ISSUE THREAD

**Issue by LayerCakeMakes** [lubeda/EsphoMaTrix#69]
The gauge seems to always start with 2 pixels even at 1% which is a loss of detail in my opinion.
It would be nice to have 12.5% per pixel (assuming 8 pixel height) or a way to configure the steps.

**Comment by lubeda** [comment]
Are you on the latest version 2023.3.5?

**Comment by LayerCakeMakes** [comment]
Ohh sorry hadn't seen the new release yet yeah it starts with one pixel now. But how are the steps defined that still seems a bit random.

**Comment by lubeda** [comment]
fixed in 2023.4.0 

Please read the **"how to update"** section in the new README.md before trying!

**Comment by LayerCakeMakes** [comment]
Thank you. I've been really enjoying playing with the notifications on my Ulanzi Clock.
