### ISSUE TITLE
How to center text?

### ISSUE THREAD

**Issue by poblabs** [lubeda/EsphoMaTrix#73]
Hi, I have the Ulanzi clock and so far so good! One question: how do I center the text? For example if I want to display the temperature, `40°`, it shows it left aligned next to icon. I'd rather it centered. Thoughts?

**Comment by lubeda** [comment]
This will come in the next release

**Comment by lubeda** [comment]
In the upcoming 2023.4.0 version short text will be centered automatically. With this small grid centering isn't that perfect, but i think a bit nicer than left aligned.

**Comment by poblabs** [comment]
Looking forward to it, thank you!
