### ISSUE TITLE
Ulanzi TC001: Mnimal Brightness

### ISSUE THREAD

**Issue by cocker-cc** [lubeda/EsphoMaTrix#74]
I found out, that the minimal Brightness for Ulanzi TC001 can be set to `30`.  Lower than that it turns completely off.  However to sleep nearby it is still too bright then for my Taste.  

Is there a Possibility to come around?

**Comment by lubeda** [comment]
Hi, i found out the the gamma correction can help. Take a look at in the esphome manual: https://esphome.io/components/light/index.html?highlight=gamma+correct
 I set mine to 1.9 and reducing the brightness works better.

If you haven't already consider giving me a star on github.  Thanx.
