### ISSUE TITLE
RTTTL ulanzi_tuneplay not working

### ISSUE THREAD

**Issue by scarolan** [lubeda/EsphoMaTrix#86]
I have a simple automation where I press the right button and call the esphome.ulanzi_tuneplay service but no sound comes out.

Could this error about GPIO15 be related?

```
GPIO15 is a Strapping PIN and should be avoided.
```

If it's any help here is my config and what I see in the logs on the device:

```
service: esphome.ulanzi_tuneplay
data:
  tune: 'Beethoven:o=5,d=4,b=160,b=160:c,e,c,g,c,c6,8b,8a,8g,8a,8g,8f,8e,8f,8e,8d,c,e,g,e,c6,g.'
```

```
11:47:03 | [E] | [rtttl:054] | Missing 'o=
```

**Comment by lubeda** [comment]
`GPIO15 is a Strapping PIN and should be avoided.` this is the strange hardware design from ulanzi! If you like my work please give me a star on github- Thanx
