### ISSUE TITLE
Schrift nach oben verschoben

### ISSUE THREAD

**Issue by frittes** [lubeda/EsphoMaTrix#90]
Hallo,

leider ist bei meiner Matrix die Schrift nach oben hin verschoben. Das Icon sowie die Balken für die Wochentage werden an der richtigen Position angezeigt. Auch wenn ich die Light-Entität aktiviere leuchten alle LEDs in weiß.

Ich habe die Standard yaml für D1 Mini mit dem entsprechenden Pixel-Mapper für die flexible Matrix verwendet.

Ist das ein Konfigurationsfehler von meiner Seite?

![IMG_2539](https://user-images.githubusercontent.com/33233288/230773020-e23c589d-304b-4601-a482-38ad33438ec1.png)

**Comment by lubeda** [comment]
Moin, abhängig von der Schriftart kannst Du die Schrift mit  `yoffset: ` nach unten schieben, eventuell musst du die Schrift auch noch verkleinern mit dem `size` parameter unter der `font` section.

Nebenbei, ich freue mich über jeden Stern auf Github und über jeden Sponsor.

**Comment by frittes** [comment]
Funktioniert, Danke!
