### ISSUE TITLE
Home Assistant "_add_screen" options

### ISSUE THREAD

**Issue by KC-inDomus** [lubeda/EsphoMaTrix#94]
Hi there,
turns out that `_add_screen` service, which seems to have `lifetime` and `screen_time` as optional fields, having them mandatory instead.
Btw, `lifetime` and `screen_time` only accept **minutes** values, while seconds would be more correct.

**Comment by lubeda** [comment]
New version will be here: [EspHoMaTriXv2](https://github.com/lubeda/EspHoMaTriXv2)

**Comment by KC-inDomus** [comment]
thanks a lot for your work!
